package com.dnd.CharacterDndBot.service.dndTable.dndService;

public enum Location {
	START, CHARACTER_CASE, CHARACTER_FACTORY, RACE_FACTORY, CLASS_FACTORY, ITEM_FACTORY, STAT_FACTORY, HP_FACTORY,
	DOWNLOAD, MENU, TEXT_COMAND, ABILITY, CHARACTERISTIC, STUFF, ROLLS, DEBUFF, REST, MEMOIRS,

}
