package app.player.model.enums;

public enum Button {

	ELIMINATION("ELIMINATION"),
	
	START("START"),
	
	CHARACTER_CASE("characterCase"),
	CREATE("CREATE"),
	DOWNLOAD("DOWNLOAD"),
	DELETE("DELETE"),
	
	MENU("Menu"),
	RETURN_TO_MENU("RETURN TO " + MENU.NAME),
	
	
	ROLLS("ROLLS"),
	
	TALENTS("TALENTS"),
	FEATURE("FEATURES"),
	SPELL("SPELLS"),
	POSSESSION("POSSESSIONS"),
	TRAIT("TRAITS"),
	FEAT("FEATS"),
	HINT_LIST("Hint list"),
	RETURN_TO_TALANT("Return to " + TALENTS.NAME),
	
	STUFF("STUFF"),
	BAG("BAG"),
	CARRYING_STUFF("PREPEARE"),
	WALLET("WALLET"),
	WEAPON("WEAPON"),
	AMNUNITION("AMNUNITION"),
	ARMOR("Armor"),
	TOOL("TOOL"),
	PACK("PACK"),
	ELSE("ELSE"),
	ADD("ADD"),
	USE("USE"),
	PREPEAR("PREPEAR"),
	WEAR("WEAR"),
	THROW_OUT("THROW OUT"),
	TOP_UP("TOP UP"),
	RETURN("RETURN"),

	ABILITY("ABILITY"),
	STAT("STATS"),
	SKILL("SKILLS"),
	SAVE_ROLL("SAVE ROLLS"),

	DEBUFF("(DE)BUFF"),
	
	MEMOIRS("MEMOIRS"),

	REST("REST"),


	ATTACK("ATTACK"),
	CRITICAL_HIT("CRIT"),
	CRITICAL_MISS("MISS"),
	ADVANTAGE("ADVANTAGE"),
	BASIC("BASIC"),
	DISADVANTAGE("DISADVANTAGE");

	Button(String name) {
		NAME = name;
	}

	public final String NAME;
}
