package app.dnd.service;

public enum Location {
	START, CHARACTER_CASE, CHARACTER_FACTORY, RACE_FACTORY, CLASS_FACTORY, ITEM_FACTORY, STAT_FACTORY, HP_FACTORY,
	DOWNLOAD_OR_DELETE, MENU, TEXT_COMAND, ABILITY, CHARACTERISTIC, STUFF, ROLLS, DEBUFF, REST, MEMOIRS, ATTACK_MACHINE,

}
